name: Feature Request
description: Suggest an idea for a feature
body:
  - type: checkboxes
    id: checks
    attributes:
      label: Checklist
      description: Please make sure you check all these items before submitting your feature request.
      options:
        - label: There are no similar issues or pull requests for this yet.
          required: true
  - type: textarea
    id: problem
    attributes:
      label: Is your feature related to a problem? Please describe.
      description: A clear and concise description of what you are trying to achieve.
      placeholder: I want to be able to [...] but I can't because [...]
  - type: textarea
    id: solution
    attributes:
      label: Describe the solution you would like.
      description: |
        A clear and concise description of what you would want to happen.
        For API changes, try to provide a code snippet of what you would like the API to look like.
  - type: textarea
    id: alternatives
    attributes:
      label: Describe alternatives you considered
      description: Please describe any alternative solutions or features you've considered to solve your problem and why they wouldn't solve it.
  - type: textarea
    id: additional
    attributes:
      label: Additional context
      description: Provide any additional context, screenshots, trace backs, etc. about the feature here.
